# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val/loss  # Changed from val/acc
  min_delta: 0.0
  patience: 100
  verbose: false
  mode: min  # Changed from max
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
