# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: checkpoints
  filename: epoch_{epoch:03d}
  monitor: val/loss  # Changed from val/acc
  verbose: false
  save_last: true
  save_top_k: 2
  mode: min  # Changed from max (lower loss is better)
  auto_insert_metric_name: false
  save_weights_only: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
